import '@/app/styles/globals.css'
import FooterSection from '@/components/ui/Footer';
import Navbar from '@/components/ui/Navbar';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js'
};

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}