import '@/app/styles/globals.css';
import FooterSection from '@/components/ui/Footer';
import Navbar from '@/components/ui/Navbar';
import BackToTop from '@/components/ui/BackToTop';
import { CartProvider } from '@/context/CartContext';
import { AuthProvider } from '@/context/AuthContext';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <Navbar />
            <main>{children}</main>
            <FooterSection />
            <BackToTop />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}